package ni.org.ics.lab.inventario.domain;

// Generated Nov 15, 2012 9:23:03 PM by Hibernate Tools 3.4.0.CR1

/**
 * RegAlicId generated by hbm2java
 */
public class RegAlicId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 368802598270509358L;
	private String codAlic;
	private int posBox;

	public RegAlicId() {
	}

	public RegAlicId(String codAlic, int posBox) {
		this.codAlic = codAlic;
		this.posBox = posBox;
	}

	public String getCodAlic() {
		return this.codAlic;
	}

	public void setCodAlic(String codAlic) {
		this.codAlic = codAlic;
	}

	public int getPosBox() {
		return this.posBox;
	}

	public void setPosBox(int posBox) {
		this.posBox = posBox;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RegAlicId))
			return false;
		RegAlicId castOther = (RegAlicId) other;

		return ((this.getCodAlic() == castOther.getCodAlic()) || (this
				.getCodAlic() != null && castOther.getCodAlic() != null && this
				.getCodAlic().equals(castOther.getCodAlic())))
				&& (this.getPosBox() == castOther.getPosBox());
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCodAlic() == null ? 0 : this.getCodAlic().hashCode());
		result = 37 * result + this.getPosBox();
		return result;
	}

}
