package ni.org.ics.lab.inventario.domain;

// Generated Nov 15, 2012 9:23:03 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import java.sql.Timestamp;
import java.util.Date;


/**
 * RegAlic generated by hbm2java
 */
@Entity
@Table(name = "reg_alic_salidas", catalog = "simlab")
public class RegSalida implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -6890416469363700411L;
	private String codigoAlic;
	private int codFreezer;
	private int posBox;
	private String codRack;
	private int codBox;
	private String negPos;
	private String volAlic;
	private Float pesoAlic;
	private String tipo;
	private String condicion;
	private String separada;
	private Date fehorReg;
	private String codUser;
	private int numDes;
	private String destAlic;
	private String userOutput;
	private Timestamp outputDate;


	public RegSalida() {
	}


	@Id
	@Column(name = "cod_alic", length =25)
	public String getCodigoAlic() {
		return codigoAlic;
	}

	public void setCodigoAlic(String codigoAlic) {
		this.codigoAlic = codigoAlic;
	}

	@Column(name = "cod_freezer", nullable = false)
	public int getCodFreezer() {
		return this.codFreezer;
	}

	public void setCodFreezer(int codFreezer) {
		this.codFreezer = codFreezer;
	}

	@Column(name = "cod_rack", length = 7, nullable = false)
	public String getCodRack() {
		return this.codRack;
	}

	public void setCodRack(String codRack) {
		this.codRack = codRack;
	}

	@Column(name = "cod_box", nullable = false)
	public int getCodBox() {
		return this.codBox;
	}

	public void setCodBox(int codBox) {
		this.codBox = codBox;
	}

	@Column(name = "neg_pos", length =3, nullable = false)
	public String getNegPos() {
		return this.negPos;
	}

	public void setNegPos(String negPos) {
		this.negPos = negPos;
	}

	@Column(name = "fehor_reg", length =19, nullable = false)
	public Date getFehorReg() {
		return this.fehorReg;
	}

	public void setFehorReg(Date fehorReg) {
		this.fehorReg = fehorReg;
	}

	@Column(name = "cod_user", length =20, nullable = false)
	public String getCodUser() {
		return this.codUser;
	}

	public void setCodUser(String codUser) {
		this.codUser = codUser;
	}

	@Column(name = "vol_alic", nullable = false)
	public String getVolAlic() {
		return volAlic;
	}

	public void setVolAlic(String volAlic) {
		this.volAlic = volAlic;
	}

	@Column(name = "peso_alic", nullable = false)
	public Float getPesoAlic() {
		return pesoAlic;
	}

	public void setPesoAlic(Float pesoAlic) {
		this.pesoAlic = pesoAlic;
	}

	@Column(name = "tipo", nullable = false, length = 20)
	public String getTipo() {
		return tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@Column(name = "condicion", length =20, nullable = false)
	public String getCondicion() {
		return condicion;
	}

	public void setCondicion(String condicion) {
		this.condicion = condicion;
	}

	@Column(name = "separada", length =20, nullable = false)
	public String getSeparada() {
		return separada;
	}

	public void setSeparada(String separada) {
		this.separada = separada;
	}

	@Column(name = "num_desc", nullable = false)
	public int getNumDes() {
		return numDes;
	}

	public void setNumDes(int numDes) {
		this.numDes = numDes;
	}

	@Column(name = "pos_box", nullable = false)
	public int getPosBox() {
		return posBox;
	}

	public void setPosBox(int posBox) {
		this.posBox = posBox;
	}

	@Column(name = "destino")
	public String getDestAlic() {
		return destAlic;
	}

	public void setDestAlic(String destAlic) {
		this.destAlic = destAlic;
	}

	@Column(name = "usuario")
	public String getUserOutput() {
		return userOutput;
	}

	public void setUserOutput(String userOutput) {
		this.userOutput = userOutput;
	}

	@Column(name = "fecha_salida")
	public Timestamp getOutputDate() {
		return outputDate;
	}

	public void setOutputDate(Timestamp outputDate) {
		this.outputDate = outputDate;
	}



	@Override
	public boolean equals(Object other) {
		
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RegSalida))
			return false;
		
		RegSalida castOther = (RegSalida) other;

		return (this.getCodigoAlic()).equals(castOther.getCodigoAlic());
	}

}
